heat_template_version: 2013-05-23

parameters:
  num_instances:
    type: number
    description: Number of instances to create
    default: 1

resources:
  compute_instances:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_instances }
      resource_def:
        type: OS::Nova::Server
        properties:
          flavor: m1.tiny
          image: cirros
          name: example group
          networks:
            - network: internal-admin

outputs:
  compute_resources:
    description: The actual compute instance details
    value: { get_attr: [compute_instances, refs]}
